# YOUR vMANAGE CREDENTIALS
VMANAGE: vmanage-test.viptela.net
PORT: 443
USERNAME: admin
PASSWORD: password123

# For Webhook Example ONLY
# WEBEX TOKEN: https://developer.webex.com/docs/getting-started
WEBEX_TOKEN: yourwebextoken1234567890
RECIPIENT: example@email.com